CREATE USER idmxinternal@localhost IDENTIFIED BY 'idmxinternal';
CREATE DATABASE idmxinternal;
GRANT ALL ON idmxinternal.* TO idmxinternal@localhost;

USE idmxinternal;

-- CLEAN DB
DROP TABLE IF EXISTS test_table;
DROP TABLE IF EXISTS state_storage_recipient;
DROP TABLE IF EXISTS state_storage_issuer;
DROP TABLE IF EXISTS pseudonym;
DROP TABLE IF EXISTS credential;
DROP TABLE IF EXISTS secret;
DROP TABLE IF EXISTS revocation_information;
DROP TABLE IF EXISTS non_revocation_evidence;
DROP TABLE IF EXISTS revocation_history;
DROP TABLE IF EXISTS rev_auth_log_entry;
DROP TABLE IF EXISTS rev_auth_params;
DROP TABLE IF EXISTS rev_auth_secret_key;
DROP TABLE IF EXISTS inspector_public_key;
DROP TABLE IF EXISTS inspector_secret_key;
DROP TABLE IF EXISTS pseudonym_in_verifier_token;
DROP TABLE IF EXISTS verifier_token;
DROP TABLE IF EXISTS issuance_log_entry;
DROP TABLE IF EXISTS pseudonym_in_issuance_token;
DROP TABLE IF EXISTS issuance_token;
DROP TABLE IF EXISTS cred_spec;
DROP TABLE IF EXISTS issuer_params;
DROP TABLE IF EXISTS issuer_secret_key;
DROP TABLE IF EXISTS system_parameters;

-- SYSTEM
CREATE TABLE system_parameters (
  id VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  data MEDIUMBLOB NOT NULL,
  CONSTRAINT PRIMARY KEY(id)
) ENGINE=InnoDB;

-- ISSUER
CREATE TABLE issuer_secret_key (
  id VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  data MEDIUMBLOB NOT NULL,
  CONSTRAINT PRIMARY KEY(id)
) ENGINE=InnoDB;

CREATE TABLE issuer_params (
  id VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  data MEDIUMBLOB NOT NULL,
  CONSTRAINT PRIMARY KEY(id)
) ENGINE=InnoDB;

CREATE TABLE cred_spec (
  id VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  data MEDIUMBLOB NOT NULL,
  CONSTRAINT PRIMARY KEY(id)
) ENGINE=InnoDB;

CREATE TABLE issuance_token (
  id VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  data MEDIUMBLOB NOT NULL,
  CONSTRAINT PRIMARY KEY(id)
) ENGINE=InnoDB;

CREATE TABLE pseudonym_in_issuance_token (
  nid INT NOT NULL AUTO_INCREMENT,
  pseudonym BLOB NOT NULL,
  tokenid VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  CONSTRAINT PRIMARY KEY(nid),
  CONSTRAINT FOREIGN KEY (tokenid) REFERENCES issuance_token(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE issuance_log_entry (
  id VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  data MEDIUMBLOB NOT NULL,
  CONSTRAINT PRIMARY KEY(id)
) ENGINE=InnoDB;

-- VERIFIER
CREATE TABLE verifier_token (
  id VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  data MEDIUMBLOB NOT NULL,
  CONSTRAINT PRIMARY KEY(id)
) ENGINE=InnoDB;

CREATE TABLE pseudonym_in_verifier_token (
  nid INT NOT NULL AUTO_INCREMENT,
  pseudonym BLOB NOT NULL,
  tokenid VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  CONSTRAINT PRIMARY KEY(nid),
  CONSTRAINT FOREIGN KEY (tokenid) REFERENCES verifier_token(id) ON DELETE CASCADE
) ENGINE=InnoDB;

-- INSPECTOR
CREATE TABLE inspector_secret_key (
  id VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  data MEDIUMBLOB NOT NULL,
  CONSTRAINT PRIMARY KEY(id)
) ENGINE=InnoDB;

CREATE TABLE inspector_public_key (
  id VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  data MEDIUMBLOB NOT NULL,
  CONSTRAINT PRIMARY KEY(id)
) ENGINE=InnoDB;

-- REVOCATION AUTHORITY
CREATE TABLE rev_auth_secret_key (
  id VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  data MEDIUMBLOB NOT NULL,
  CONSTRAINT PRIMARY KEY(id)
) ENGINE=InnoDB;

CREATE TABLE rev_auth_params (
  id VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  data MEDIUMBLOB NOT NULL,
  CONSTRAINT PRIMARY KEY(id)
) ENGINE=InnoDB;

CREATE TABLE rev_auth_log_entry (
  id VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  data MEDIUMBLOB NOT NULL,
  CONSTRAINT PRIMARY KEY(id)
) ENGINE=InnoDB;

CREATE TABLE revocation_history (
  id VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  data MEDIUMBLOB NOT NULL,
  CONSTRAINT PRIMARY KEY(id)
) ENGINE=InnoDB;

CREATE TABLE non_revocation_evidence (
  id VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  data MEDIUMBLOB NOT NULL,
  CONSTRAINT PRIMARY KEY(id)
) ENGINE=InnoDB;

CREATE TABLE revocation_information (
  id VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  rev_auth VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  created DATETIME NOT NULL,
  data MEDIUMBLOB NOT NULL,
  CONSTRAINT PRIMARY KEY(id, rev_auth),
  INDEX(rev_auth,created)
) ENGINE=InnoDB;

-- USER
CREATE TABLE secret (
  id VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  username VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  data MEDIUMBLOB NOT NULL,
  CONSTRAINT PRIMARY KEY(username, id)
) ENGINE=InnoDB;

CREATE TABLE credential (
  id VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  username VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  issuer VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  credspec VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  data MEDIUMBLOB NOT NULL,
  CONSTRAINT PRIMARY KEY(id, username),
  INDEX(username, issuer, credspec)
) ENGINE=InnoDB;

CREATE TABLE pseudonym (
  id VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  username VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  scope VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  exclusive BOOLEAN NOT NULL,
  pseudonym BLOB NOT NULL,
  data MEDIUMBLOB NOT NULL,
  CONSTRAINT PRIMARY KEY(id, username),
  INDEX(username, scope, exclusive)
) ENGINE=InnoDB;

CREATE TABLE state_storage_issuer (
  id VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  data MEDIUMBLOB NOT NULL,
  date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT PRIMARY KEY(id)
) ENGINE=InnoDB;

CREATE TABLE state_storage_recipient (
  id VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  data MEDIUMBLOB NOT NULL,
  date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT PRIMARY KEY(id)
) ENGINE=InnoDB;

CREATE TABLE test_table (
  id VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  data MEDIUMBLOB NOT NULL,
  CONSTRAINT PRIMARY KEY(id)
) ENGINE=InnoDB;
